CI -> default mpirun

diff --git a/script/pdm_run.in b/script/pdm_run.in
--- a/script/pdm_run.in
+++ b/script/pdm_run.in
@@ -153,7 +153,6 @@ do
   ((j=i+1))
   printf  "${PURPLE}[%3.3d/%3.3d] - %s: Start${NC}\n" ${j} ${nTest} ${TestName} 
   
-  start=$(($(date +%s%N)/1000000))
 
   #
   # Cleanup
@@ -163,26 +162,22 @@ do
   #
   # Run test
   Testoutput=0
-  
+  pids=()
+
+
   if [ ${IsSrunMPI} -gt 0 ]
   then
     if [ $isPythonTest -gt 0  ]
     then
       ${ExeMPI} --verbose --export=@PDM_RUN_PRELOAD_SRUN@,@PDM_RUN_LSAN@,@PDM_RUN_PYTHONPATH@  --output=$OutputFile.%t --error$ErrFile.%t --ntasks=$Nrank  --exclusive /usr/bin/time  -f "Maximum Resident Memory : %M Kb" python ./${TestName}.py ${TestOption} 2>/dev/null &
-#      ${ExeMPI} --verbose  --output=$OutputFile.%t --error$ErrFile.%t --ntasks=$Nrank  --exclusive /usr/bin/time  -f "Maximum Resident Memory : %M Kb" python ${TestName}.py ${TestOption} 2>/dev/null &
-      if [ "$?" -ne "0" ]
-      then
-        Testoutput=1
-      fi
     else
       ${ExeMPI} --verbose --export=@PDM_RUN_PRELOAD_SRUN@,@PDM_RUN_LSAN@ --output=$OutputFile.%t --error$ErrFile.%t --ntasks=$Nrank  --exclusive /usr/bin/time  -f "Maximum Resident Memory : %M Kb" ./${TestName} ${TestOption} &
-#      ${ExeMPI} --verbose  --output=$OutputFile.%t --error$ErrFile.%t --ntasks=$Nrank  --exclusive /usr/bin/time  -f "Maximum Resident Memory : %M Kb" python ${TestName} ${TestOption} 2>/dev/null &
-      if [ "$?" -ne "0" ]
-      then
-        Testoutput=1
-      fi
     fi
+    pids=(${pids[@]} "$!")
   else  
+
+    start=$(($(date +%s%N)/1000000))
+
     if [ ${IsIntelMPI} -gt 0 ]
     then
       if [ $isPythonTest -gt 0  ]
@@ -209,108 +204,114 @@ do
         Testoutput=1
       fi
     fi
-  fi
     
-  end=$(($(date +%s%N)/1000000))
+    end=$(($(date +%s%N)/1000000))
   
-  #
-  # Compute elapsed time
-  
-  elapsed=$(echo "scale=2; ($end-$start)/1000" | bc)
-  
-  #
-  # Check Maximum Resident memory
-  
-  max="-1"
-  min="10000000"
-  
-  minRank=-1
-  maxRank=-1
-  rank=0
-  
-  if [ ${IsIntelMPI} -gt 0 ]
-  then
-    listErrFile=$(ls $ErrFile.*)
-  else
-    listErrFile=$(find $OutputFile -name stderr)
-  fi
-  
-  for file in ${listErrFile}
-  do
-    v=$(grep -m 1 "Maximum Resident Memory" $file | awk '{print $5}')
-    maxRank=$(echo "if($v>$max) $rank else $maxRank" | bc)
-    minRank=$(echo "if($v<$min) $rank else $minRank" | bc)
-    max=$(echo "if($v>$max) $v else $max" | bc)
-    min=$(echo "if($v<$min) $v else $min" | bc)
-    rank=$((rank+1))
-  done
-  
-  maxM=$(echo "scale=2; $max/1000" | bc)
-  minM=$(echo "scale=2; $min/1000" | bc)
-  
-  echo "    Maximum of Maximum Resident Memory: ${maxM} Mb on rank ${maxRank}"
-  echo "    Minimum of Maximum Resident Memory: ${minM} Mb on rank ${minRank}"
-  
-  #
-  # Check *vtk and *log file
-  
-  val_vtk=`ls -l *.vtk  2> /dev/null | wc -l`;
-  val_log=`ls -l *.log  2> /dev/null | wc -l`;
-  
-  if [ $val_vtk -gt 0 ] || [ $val_log -gt 0 ]
-  then
-    echo "    Number of vtk files = ${val_vtk}"
-    echo "    Number of log files = ${val_log}"
-  fi
-  
-  #
-  # Exit
-  
-  if [ "${ForbidVtk}" -eq "1" ]
-  then
-    if [ ${val_vtk} -gt 0 ] || [ ${val_log} -gt 0 ]
+    #
+    # Compute elapsed time
+    
+    elapsed=$(echo "scale=2; ($end-$start)/1000" | bc)
+    
+    #
+    # Check Maximum Resident memory
+    
+    max="-1"
+    min="10000000"
+    
+    minRank=-1
+    maxRank=-1
+    rank=0
+    
+    if [ ${IsIntelMPI} -gt 0 ]
     then
-      if [ "${Testoutput}" -gt "0" ]
+      listErrFile=$(ls $ErrFile.*)
+    else
+      listErrFile=$(find $OutputFile -name stderr)
+    fi
+    
+    for file in ${listErrFile}
+    do
+      v=$(grep -m 1 "Maximum Resident Memory" $file | awk '{print $5}')
+      maxRank=$(echo "if($v>$max) $rank else $maxRank" | bc)
+      minRank=$(echo "if($v<$min) $rank else $minRank" | bc)
+      max=$(echo "if($v>$max) $v else $max" | bc)
+      min=$(echo "if($v<$min) $v else $min" | bc)
+      rank=$((rank+1))
+    done
+    
+    maxM=$(echo "scale=2; $max/1000" | bc)
+    minM=$(echo "scale=2; $min/1000" | bc)
+    
+    echo "    Maximum of Maximum Resident Memory: ${maxM} Mb on rank ${maxRank}"
+    echo "    Minimum of Maximum Resident Memory: ${minM} Mb on rank ${minRank}"
+    
+    #
+    # Check *vtk and *log file
+    
+    val_vtk=`ls -l *.vtk  2> /dev/null | wc -l`;
+    val_log=`ls -l *.log  2> /dev/null | wc -l`;
+    
+    if [ $val_vtk -gt 0 ] || [ $val_log -gt 0 ]
+    then
+      echo "    Number of vtk files = ${val_vtk}"
+      echo "    Number of log files = ${val_log}"
+    fi
+    
+    #
+    # Exit
+    
+    if [ "${ForbidVtk}" -eq "1" ]
+    then
+      if [ ${val_vtk} -gt 0 ] || [ ${val_log} -gt 0 ]
       then
-        echo -e "    ${NC}Error${NC}: Test exited on Error"
+        if [ "${Testoutput}" -gt "0" ]
+        then
+          echo -e "    ${NC}Error${NC}: Test exited on Error"
+        fi
+        echo -e "    ${RED}Error${NC}: *vtk and *log files are not allowed"
+        printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j} ${nTest} ${TestName} 
+        Testoutput=1
+      else
+        if [ "${Testoutput}" -eq "0" ]
+        then
+          printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${GREEN}Passed${NC} - %s s\n" ${j} ${nTest} ${TestName}  ${elapsed}
+        else
+          echo -e "    ${RED}Error${NC}: Test exited on Error"
+          printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j} ${nTest} ${TestName} 
+        fi
       fi
-      echo -e "    ${RED}Error${NC}: *vtk and *log files are not allowed"
-      printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j} ${nTest} ${TestName} 
-      Testoutput=1
     else
       if [ "${Testoutput}" -eq "0" ]
       then
-        printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${GREEN}Passed${NC} - %s s\n" ${j} ${nTest} ${TestName}  ${elapsed}
+        printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${GREEN}Passed${NC} - %s s\n" ${j} ${nTest} ${TestName} ${elapsed} 
       else
-        echo -e "    ${RED}Error${NC}: Test exited on Error"
         printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j} ${nTest} ${TestName} 
       fi
     fi
-  else
-    if [ "${Testoutput}" -eq "0" ]
+
+    scriptOutput=$(echo "if($Testoutput>$scriptOutput) $Testoutput else $scriptOutput" | bc)
+   
+    ((i=i+1))
+
+    if [ "${Testoutput}" -ne "0" ]
     then
-      printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${GREEN}Passed${NC} - %s s\n" ${j} ${nTest} ${TestName} ${elapsed} 
-    else
-      printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j} ${nTest} ${TestName} 
-    fi
-  fi
-
-  scriptOutput=$(echo "if($Testoutput>$scriptOutput) $Testoutput else $scriptOutput" | bc)
- 
-  ((i=i+1))
-
-  if [ "${Testoutput}" -ne "0" ]
-  then
-    ((ifailed=ifailed+1))
+      ((ifailed=ifailed+1))
+    fi  
   fi  
-
 done
 
 if [ ${IsSrunMPI} -gt 0 ]
 then
-  wait
+  for pid in "${pids[@]}"
+  do
+    wait $pid
+    if [ "$?" -ne "0" ]
+    then
+      Testoutput=1
+    fi
+  done  
 fi
 
-printf  "      ${PURPLE}%3.3d tests failed out of %3.3d\n${NC}" ${ifailed} ${nTest} 
+printf  "\n      ${PURPLE}%3.3d tests failed out of %3.3d\n${NC}" ${ifailed} ${nTest} 
 
 exit ${scriptOutput}
