add srun into pdm_run

diff --git a/script/pdm_run.in b/script/pdm_run.in
--- a/script/pdm_run.in
+++ b/script/pdm_run.in
@@ -12,7 +12,7 @@ Help()
 {
   echo "Run a pdm test case. (without \"-t\" option, run all tests with default rank number)"
   echo
-  echo "Syntax: pdm_run [-m|mpiexec|no_log_vtk|h] -n <number of ranks> -t <test name and its options>"
+  echo "Syntax: pdm_run [-m|mpiexec|no_log_vtk|h|n_avail_rank] -n <number of ranks> -t <test name and its options>"
   echo "options:"
   echo "m                                  Make test before run"
   echo "h                                  Print this Help"
@@ -20,12 +20,14 @@ Help()
   echo "srun                               Run with mpiexec command (default : mpirun)"
   echo "n <number of ranks>                Number of ranks (default : 2)"
   echo "no_log_vtk                         Exit on error if test writes some log and vtk files"
+  echo "n_avail_rank                       Number of available ranks for script"
   echo "t <\"test name and its options\">  Test name and its options "
   echo
 }
 
 Dump_mem()
 {
+  cd ${TestName1}_d 
   max="-1"
   min="10000000"
   
@@ -55,11 +57,12 @@ Dump_mem()
   
   echo "    Maximum of Maximum Resident Memory: ${maxM} Mb on rank ${maxRank}"
   echo "    Minimum of Maximum Resident Memory: ${minM} Mb on rank ${minRank}"
-
+  cd ..
 }
 
 Dump_time()
 {
+  cd ${TestName1}_d 
   max="-1"
   
   maxRank=-1
@@ -80,11 +83,12 @@ Dump_time()
   done
   
   echo $max
-
+  cd ..
 }
 
 Dump_nb_log_vtk_file()
 {
+  cd ${TestName1}_d 
   val_vtk=`ls -l *.vtk  2> /dev/null | wc -l`;
   val_log=`ls -l *.log  2> /dev/null | wc -l`;
 
@@ -93,7 +97,90 @@ Dump_nb_log_vtk_file()
     echo "    Number of vtk files = ${val_vtk}"
     echo "    Number of log files = ${val_log}"
   fi
+  cd ..
 }
+
+Wait_job()
+{
+  i1=$Indextest
+  ((j1=Indextest+1))
+  for pid in "${pids[@]}"
+  do
+    Testoutput=0
+    TestName1=$(echo ${listComputedTest[$i1]} | awk '{print $1}')
+    OutputFile1=$(echo ${TestName1}${postOutput})
+    ErrFile1=$(echo ${TestName1}${postErr})
+
+    printf  "${PURPLE}[%3.3d/%3.3d] - %s: Finalize${NC}\n" ${j1} ${nTest} ${TestName1} 
+
+    wait $pid
+
+    if [ "$?" -ne "0" ]
+    then
+      Testoutput=1
+      printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j1} ${nTest} ${TestName1}
+      failedTest=(${failedTest[@]} "$i1")
+ 
+      ((ifailed=ifailed+1))
+    else        
+
+      #
+      # Compute elapsed time
+      
+      elapsed=$(Dump_time $ErrFile1 $OutputFile1)
+
+      #
+      # Check Maximum Resident memory
+
+      Dump_mem $ErrFile1 $OutputFile1
+
+      #
+      # Check *vtk and *log file
+      
+      Dump_nb_log_vtk_file ${TestName1}
+    
+      if [ "${ForbidVtk}" -eq "1" ]
+      then
+        if [ ${val_vtk} -gt 0 ] || [ ${val_log} -gt 0 ]
+        then
+          if [ "${Testoutput}" -gt "0" ]
+          then
+            echo -e "    ${NC}Error${NC}: Test exited on Error"
+          fi
+          echo -e "    ${RED}Error${NC}: *vtk and *log files are not allowed"
+          printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j1} ${nTest} ${TestName1} 
+          Testoutput=1
+        else
+          if [ "${Testoutput}" -eq "0" ]
+          then
+            printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${GREEN}Passed${NC} - %s s\n" ${j1} ${nTest} ${TestName1}  ${elapsed}
+          else
+            echo -e "    ${RED}Error${NC}: Test exited on Error"
+            printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j1} ${nTest} ${TestName1} 
+          fi
+        fi
+      else
+        if [ "${Testoutput}" -eq "0" ]
+        then
+          printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${GREEN}Passed${NC} - %s s\n" ${j1} ${nTest} ${TestName1} ${elapsed} 
+        else
+          printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j1} ${nTest} ${TestName1} 
+        fi
+      fi
+
+    fi
+    ((i1=i1+1))
+    ((j1=j1+1))
+    scriptOutput=$(echo "if($Testoutput>$scriptOutput) $Testoutput else $scriptOutput" | bc)
+  done
+
+  IndexRank=0  
+  pids=() 
+
+}
+
+
+start=$(($(date +%s%N)/1000000))
 
 # Get the options 
 
@@ -104,6 +191,8 @@ NrankUser=0
 runMake=0
 Test=""
 IsSrunMPI=0
+NAvailRank=24
+failedTest=()
 
 while [ -n "$1" ]
 do
@@ -117,6 +206,8 @@ case "$1" in
     -srun) ExeMPI="srun"
               IsSrunMPI=1;;
     -no_log_vtk) ForbidVtk=1;;
+    -n_avail_rank) NAvailRank="$2"
+        shift;;
     -h) Help
         exit;;
     *) echo "Error : $1 is not an option"
@@ -165,6 +256,9 @@ nTest=${#listComputedTest[@]}
 scriptOutput=0
 pids=()
 
+IndexRank=0
+Indextest=0
+cptRank=0
 
 for x in "${listComputedTest[@]}"
 do
@@ -241,93 +335,48 @@ do
   then
     if [ $isPythonTest -gt 0  ]
     then
-      ${ExeMPI} --verbose --export=@PDM_RUN_PRELOAD_SRUN@,@PDM_RUN_LSAN@,@PDM_RUN_PYTHONPATH@  --output=$OutputFile.%t --error=$ErrFile.%t -n$Nrank  /usr/bin/time  -f "Maximum Resident Memory : %M Kb\nReal time : %e s" python ./${TestName}.py ${TestOption} 2>/dev/null &
+      ${ExeMPI} --verbose --export=ALL,@PDM_RUN_PRELOAD_SRUN@,@PDM_RUN_LSAN@,@PDM_RUN_PYTHONPATH@  --output=$OutputFile.%t --error=$ErrFile.%t -n$Nrank  /usr/bin/time  -f "Maximum Resident Memory : %M Kb\nReal time : %e s" python ./${TestName}.py ${TestOption} 2>/dev/null &
     else
-      ${ExeMPI} --verbose --export=@PDM_RUN_PRELOAD_SRUN@,@PDM_RUN_LSAN@ --output=$OutputFile.%t --error=$ErrFile.%t -n$Nrank  /usr/bin/time  -f "Maximum Resident Memory : %M Kb\nReal time : %e s" ./${TestName} ${TestOption}   &
+      ${ExeMPI} --verbose --export=ALL,@PDM_RUN_PRELOAD_SRUN@,@PDM_RUN_LSAN@ --output=$OutputFile.%t --error=$ErrFile.%t -n$Nrank  /usr/bin/time  -f "Maximum Resident Memory : %M Kb\nReal time : %e s" ./${TestName} ${TestOption}   &
     fi
     pids=(${pids[@]} "$!")
   else  
 
+    if [ $Nrank -gt $NAvailRank ]
+    then
+      echo "Error PDM_run : Number of requested ranks is greater then the number of available ranks"
+      exit 1
+    fi  
+
+    ((cptRank=IndexRank+Nrank)) 
+    
+    if [ $cptRank -gt $NAvailRank ]
+    then
+      Wait_job
+      Indextest=$i
+    fi
+
+    mkdir -p ${TestName}_d
+    cd ${TestName}_d  
     if [ ${IsIntelMPI} -gt 0 ]
     then
       if [ $isPythonTest -gt 0  ]
       then
-        @PDM_RUN_LSAN@ @PDM_RUN_PYTHONPATH@ ${ExeMPI} -genv @PDM_RUN_PRELOAD@ -outfile-pattern $OutputFile.%r -errfile-pattern $ErrFile.%r -n $Nrank /usr/bin/time  -f "Maximum Resident Memory : %M Kb\nReal time : %e s" python ./${TestName}.py ${TestOption} 2>/dev/null
-        if [ "$?" -ne "0" ]
-        then
-          Testoutput=1
-        fi
+        @PDM_RUN_LSAN@ @PDM_RUN_PYTHONPATH@ ${ExeMPI} -genv @PDM_RUN_PRELOAD@ -outfile-pattern $OutputFile.%r -errfile-pattern $ErrFile.%r -n $Nrank /usr/bin/time  -f "Maximum Resident Memory : %M Kb\nReal time : %e s" python ../${TestName}.py ${TestOption} 2>/dev/null &
       else
-        @PDM_RUN_LSAN@ ${ExeMPI} -genv @PDM_RUN_PRELOAD@ -outfile-pattern $OutputFile.%r -errfile-pattern $ErrFile.%r  -n $Nrank /usr/bin/time  -f "Maximum Resident Memory : %M Kb\nReal time : %e s" ./${TestName} ${TestOption} 2>/dev/null
-        if [ "$?" -ne "0" ]
-        then
-          Testoutput=1
-        fi
+        @PDM_RUN_LSAN@ ${ExeMPI} -genv @PDM_RUN_PRELOAD@ -outfile-pattern $OutputFile.%r -errfile-pattern $ErrFile.%r  -n $Nrank /usr/bin/time  -f "Maximum Resident Memory : %M Kb\nReal time : %e s" ../${TestName} ${TestOption} 2>/dev/null &
       fi
+      pids=(${pids[@]} "$!")
     else
       echo -e "${RED}Error${NC}: OpenMPI is not available for pdm_run script"
       echo -e "${PURPLE}${TestName}: ${RED}Failed${NC}"
       exit 1
-      @PDM_RUN_LSAN@ @PDM_RUN_PYTHONPATH@ ${ExeMPI} -genv @PDM_RUN_PRELOAD@ -output-filename $OutputFile -n $Nrank /usr/bin/time  -f "Maximum Resident Memory : %M Kb\nReal time : %e s" ./${TestName} ${TestOption} 2>/dev/null
-      if [ "$?" -ne "0" ]
-      then
-        Testoutput=1
-      fi
+      @PDM_RUN_LSAN@ @PDM_RUN_PYTHONPATH@ ${ExeMPI} -genv @PDM_RUN_PRELOAD@ -output-filename $OutputFile -n $Nrank /usr/bin/time  -f "Maximum Resident Memory : %M Kb\nReal time : %e s" ../${TestName} ${TestOption} 2>/dev/null
+      pids=(${pids[@]} "$!")
     fi
-    
-    #
-    # Compute elapsed time
-    
-    elapsed=$(Dump_time $ErrFile $OutputFile)
-
-    #
-    # Check Maximum Resident memory
-
-    Dump_mem $ErrFile $OutputFile
-
-    #
-    # Check *vtk and *log file
-    
-    Dump_nb_log_vtk_file
+    cd ..
+    ((IndexRank=IndexRank+Nrank)) 
   
-    #
-    # Exit
-    
-    if [ "${ForbidVtk}" -eq "1" ]
-    then
-      if [ ${val_vtk} -gt 0 ] || [ ${val_log} -gt 0 ]
-      then
-        if [ "${Testoutput}" -gt "0" ]
-        then
-          echo -e "    ${NC}Error${NC}: Test exited on Error"
-        fi
-        echo -e "    ${RED}Error${NC}: *vtk and *log files are not allowed"
-        printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j} ${nTest} ${TestName} 
-        Testoutput=1
-      else
-        if [ "${Testoutput}" -eq "0" ]
-        then
-          printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${GREEN}Passed${NC} - %s s\n" ${j} ${nTest} ${TestName}  ${elapsed}
-        else
-          echo -e "    ${RED}Error${NC}: Test exited on Error"
-          printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j} ${nTest} ${TestName} 
-        fi
-      fi
-    else
-      if [ "${Testoutput}" -eq "0" ]
-      then
-        printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${GREEN}Passed${NC} - %s s\n" ${j} ${nTest} ${TestName} ${elapsed} 
-      else
-        printf  "${PURPLE}[%3.3d/%3.3d] - %s: ${RED}Failed${NC}\n" ${j} ${nTest} ${TestName} 
-      fi
-    fi
-
-    scriptOutput=$(echo "if($Testoutput>$scriptOutput) $Testoutput else $scriptOutput" | bc)
-
-    if [ "${Testoutput}" -ne "0" ]
-    then
-       ((ifailed=ifailed+1))
-    fi  
   fi  
 
   ((i=i+1))
@@ -366,9 +415,20 @@ then
     ((i=i+1))
     ((j=j+1))
     scriptOutput=$(echo "if($Testoutput>$scriptOutput) $Testoutput else $scriptOutput" | bc)
-  done  
+  done 
+
+else 
+  Wait_job
 fi
 
-printf  "\n      ${PURPLE}%3.3d tests failed out of %3.3d\n${NC}" ${ifailed} ${nTest} 
+printf  "\n      ${PURPLE}%3.3d tests failed out of %3.3d : \n${NC}" ${ifailed} ${nTest} 
+for i in "${failedTest[@]}"
+do
+  TestName=$(echo ${listComputedTest[$i]} | awk '{print $1}')
+  echo "          - $TestName"
+done
+end=$(($(date +%s%N)/1000000))
+elapsed=$(echo "scale=2; ($end-$start)/1000" | bc)
+echo "elapsed job = ${elapsed} s"
 
 exit ${scriptOutput}
